networks:
  singularnet:
    driver: bridge

services:
  db:
    container_name: singular-db
    image: postgres:17.6-alpine3.21
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - singularnet
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

  adminer:
    container_name: singular-adminer
    image: dockette/adminer:pgsql
    ports:
      - "8080:8080"
    networks:
      - singularnet
    depends_on:
      db:
        condition: service_healthy
